apiVersion: apps/v1
kind: Deployment
metadata:
  name: intercom-sink-deployment
  labels:
    workbenchdata.com/uses-rabbitmq: "true"
spec:
  selector:
    matchLabels:
      app: intercom-sink-app
  template:
    metadata:
      labels:
        app: intercom-sink-app
    spec:
      containers:
      - name: app
        image: "848416313321.dkr.ecr.eu-west-1.amazonaws.com/workbench:632e44285e65d97fcedebddd5ac12c37ff62c431"
        resources:
          requests:
            cpu: 150m
            memory: 300Mi
          limits:
            cpu: 150m
            memory: 300Mi
        env:
        - name: CJW_INTERCOM_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cjw-intercom-sink-intercom-secret
              key: ACCESS_TOKEN
        - name: CJW_INTERCOM_QUEUE_NAME
          value: intercom
